# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
minimal_mistakes_skin: dark
repository: k0staa/k0staa.github.io
remote_theme: mmistakes/minimal-mistakes
# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
search: true





locale                   : "pl"
title                    : "code-addict"
title_separator          : "-"
name                     : "Michał Kostewicz"
description              : "Blog about software development. It's my hobby to write lines of code and deepen new technologies and I'd like to share my passion with you! I will write about Java, Python, C#, C++,relational and not relational databases, machine learning, data mining... so about everything really."
url                      : "http://code-addict.pl"
baseurl                  : # the subpath of your site, e.g. "/blog"
teaser                   : "/assets/images/default_post_teaser.jpg"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "master"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "docs/_data/comments/{options.slug}" # "/_data/comments/{options.slug}" (default)
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
atom_feed:
  path                   : #"_site/feed.xml"


# SEO Related
google_site_verification : "SE64OGz2ULNry6QXWhlJScUfNUXwifw-VjYwdRPyCdU"
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :



# Social Sharing
twitter:
  username               : "MKostewicz"
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : "Michał Kostewicz"
  name                   : # If the user or organization name differs from the site's name
  links: 
    - "https://twitter.com/MKostewicz"
    - "https://www.facebook.com/mK0sta"
    - "https://www.linkedin.com/in/micha%C5%82-kostewicz-49565213a/"


# Analytics
analytics:
  provider               : "google" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-102651793-1"


google_ad_client        : true


# Site Author
author:
  name             : "Michał Kostewicz"
  avatar           : "/assets/images/my-photo.jpg"
  bio              : "Hi! I'm Michał Kostewicz, creator of this blog. I'm living in Warsaw, Poland. I am a programmer by profession but it is also one of my passions. I'm using mostly Java but it is just a tool for me so I often use other languages. I have wonderful wife and daughter that I loved even more than my job."
  location         : "Warsaw, Poland"
  email            : "m.kostewicz84@gmail.com"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "k0staa"
  gitlab           :
  google_plus      : "MichałKostewicz"
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : "michał-kostewicz-49565213a"
  pinterest        :
  soundcloud       :
  stackoverflow    : "4568484/k0staa" # (the last part of your profile url, e.g. http://stackoverflow.com/users/123456/username)
  steam            :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  xing             :
  youtube          : # "https://youtube.com/c/MichaelRoseDesign"

  
# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "Europe/Warsaw"  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

  
# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

